### ISSUE TITLE
How to obtain attribute estimates from estQ()

### ISSUE THREAD

**Issue by cwliu007** [Pablo-Najera/cdmTools#1]
Hello Pablo,

I wonder if it is possible to return the attribute estimates from estQ()? I think it is possible. It will be most appreciated if you could let me know how to do it. 

Many thanks for the useful package!

CW

**Comment by Pablo-Najera** [comment]
Hi!

The function `estQ` only provides an empirically estimated Q-matrix from the data. The suggested Q-matrix can be then used to estimate a model (e.g., G-DINA), from which attribute estimates can be retrieved. The following toy code illustrates how to do it using both the `cdmTools` and `GDINA` packages:

```
library(cdmTools)
library(GDINA)
dat <- GDINA::sim30GDINA$simdat # Illustrative dataset
Q <- cdmTools::estQ(dat, K = 5) # Empirical Q-matrix estimation
fit <- GDINA::GDINA(dat, Q$est.Q, model = "GDINA") # Fit a G-DINA model using the estimated Q-matrix
GDINA::personparm(fit) # Obtain the attribute profile classifications
```

Hope this helps. Thank you for using the package and for asking!

Pablo

**Comment by cwliu007** [comment]
I appreciate your insightful reply. Thank you!
